---
- name: Ensure VirtualBox dnf repo exists
  get_url:
    url: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo
    mode: 0644

- name: Ensure VirtualBox is installed
  dnf:
    name: VirtualBox-5.1
    state: present
    enablerepo: virtualbox
